#!/bin/sh

ERLANG_NODE=ejabberd@localhost

if [ -f /etc/default/ejabberd-snapshot ] ; then
    . /etc/default/ejabberd-snapshot
fi

if [ -r /var/lib/ejabberd/.erlang.cookie ] ; then
    HOME=/var/lib/ejabberd
    export HOME
fi

ERL=/usr/bin/erl
EBIN_DIR=/usr/lib/ejabberd/ebin

if [ $# -ne 0 ] ; then
    case $1 in
	--) shift; break ;;
	--node) shift ; ERLANG_NODE=$1 ; shift ;;
    esac
fi

if [ "$ERLANG_NODE" = "${ERLANG_NODE%.*}" ] ; then
    SNAME=-sname
else
    SNAME=-name
fi

SUFFIX=$(date +%s%N)

case $1 in
    debug)
	shift

	if [ "$ERLANG_NODE" = "${ERLANG_NODE%@*}" ] ; then
	    ERLANG_NODE=$ERLANG_NODE@$(hostname -s)
	fi

	echo "Attaching Erlang shell to node $ERLANG_NODE."
	echo "To detach it, press: Ctrl+G, q, Return"
	echo ""
	exec $ERL $SNAME ejabberddebug$SUFFIX \
	    -remsh $ERLANG_NODE \
	    "$@"
    ;;
    *)
	exec $ERL $SNAME ejabberdctl$SUFFIX \
	    -pa $EBIN_DIR \
	    -s ejabberd_ctl \
	    -noinput \
	    -extra $ERLANG_NODE "$@"
    ;;
esac
